sudo: false
language: python
matrix:
  include:
    - python: 3.6
      env: TOX_ENV=py36
    - python: 3.7
      dist: xenial
      sudo: true
      env: TOX_ENV=py37
    - python: 3.8
      dist: xenial
      sudo: true
      env: TOX_ENV=py38
    - python: 3.9
      dist: xenial
      sudo: true
      env: TOX_ENV=py39
    - python: 3.9
      dist: xenial
      sudo: true
      env: TOX_ENV=flake8
cache: pip
install:
  - "travis_retry pip install setuptools --upgrade"
  - "travis_retry pip install tox"
  - "travis_retry pip install codecov"
script:
  - tox -e $TOX_ENV
after_success:
  - test $TOX_ENV == "py38" && codecov
